--AutoGenerated by DEVotion

function load()
image = love.grapchics.newImage("images/padariukas.bmp");
end

function update(dt)
end



function draw()
	love.prapchis.draw(image,300,400);
end
